#!/bin/bash

echo "Running prepare-commit-msg script..."
echo "Commit message file: $1"

if [ ! -f "$1" ]; then
  echo "Commit message file not found!"
  exit 1
fi

jira-prepare-commit-msg "$1"

# TICKET_ID 추출
TICKET_ID=$(egrep -o 'GN-[0-9]+' "$1")

if [ -n "$TICKET_ID" ]; then
  if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS에서 sed 사용
    sed -i '' 's/\[GN-[0-9]*\]//g' "$1"
    sed -i '' "s/^\(.*\): \(.*\)$/\1($TICKET_ID): \2/" "$1"
  else
    # Linux 및 기타 Unix 시스템에서 sed 사용
    sed -i 's/\[GN-[0-9]*\]//g' "$1"
    sed -i "s/^\(.*\): \(.*\)$/\1($TICKET_ID): \2/" "$1"
  fi
else
  echo "No ticket ID found."
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  sed -i '' $'s/^[ \t]*//;s/[ \t]*$//' "$1"
else
  sed -i 's/^[ \t]*//;s/[ \t]*$//' "$1"
fi

echo "Script finished."
